[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^3.11.0
	mikalhart/TinyGPSPlus@^1.0.3
